### PR TITLE
Refactor: Introduce Scalafix and Lint / Refactor the code

### PR DESCRIPTION
**Pull request by Javakky-pxv**
Look after this because of the dependencies of the pr: https://github.com/iheartradio/play-swagger/pull/462

[scalafix](https://scalacenter.github.io/scalafix/) is a Linter and refactoring tool designed for Scala.
It can automatically respond to compiler warnings by introducing some useful settings such as import alignment.
The rules described here only work with Scala 2.12 series, but you can use them for various code conditions if you try hard enough. (e.g. The rules I have: https://github.com/pixiv/scalafix-pixiv-rule)

Although this tool is slower than scalafmt, we ask that you consider it, as its introduction would improve the development experience 🙇

### CODE REVIEW

**Comment by Javakky-pxv** [comment]
You can run scalafmt with the following command.
It is recommended to run scalafmt after running scalafix, as the style may be broken.

```sh
sbt scalafixAll scalafmtAll
```

**Comment by kailuowang** [comment]
Hi @Javakky-pxv, thanks so much for your contributions. Will you be interested in becoming a maintainer of play-swagger. I myself have stopped using the play framework for years so I've been neglecting it. It will be really nice to have a maintainer who is invested in the project like you do. Please let me know.

**Comment by Javakky-pxv** [comment]
@kailuowang Thank you.
It is a great honor and I would love to try.
However, there is a part of me that does not have a deep understanding of what it means to be a maintainer. Can you tell me what powers and duties this would entail?

Here is what I am thinking right now.

What I want to do :
- Release
- Version updates of dependencies
- Propose new features
- Respond to issues whenever possible

What I am worried about:
- I'm still a novice engineer, and without reviewers, I might break the existing spec.
- Does participating in your repository entail any responsibilities? (e.g. total hours spent working, Quality Assurance)

**Comment by Javakky-pxv** [comment]
Once again, this proposal is very attractive to me. By all means, let me continue to cooperate with you!

**Comment by kailuowang** [comment]
@Javakky-pxv that's awesome!!! I'm very excited to welcome you. 
As a maintainer of play-swagger, you will be able to merge PRs, and the only requirement is that you merge PRs based on your judgment on whether the PR is net beneficial to the whole user/contributor community (yourself included). That's it. There are absolutely no requirements for hours or anything like that. 

As for the other things on your "I want to do" list, you are more than welcome to do whatever you think is good for the project and community. (Other contributors are welcome to do that as well)

I will remain a maintainer to help reviews, particularly your PR upon your request. 
Releasing will remain my responsibility for now since it requires publishing auth for the iHeartRadio (my company)'s org. I will fully support if you wish to move play-swagger to its own org so that any maintainers can release.

I am sending you an invite to the project soon.

**Comment by Javakky-pxv** [comment]
@kailuowang 
Thank you!
I have agreed to be a maintainer.
As soon as possible, I would like to merge the introductory PRs for scalafmt and scalafix.

**Pull request merged**
