### PR TITLE
upgrade dependencies to match those of Play 2.7

### PR DESCRIPTION
**Pull request by mihaisoloi**
One of the tests is failing, I have to fix it, or if anyone gets to it before me, I won't mind

### CODE REVIEW

**Comment by mihaisoloi** [comment]
This is meant to solve #239

**Comment by mihaisoloi** [comment]
for some reason I keep getting `javax.net.ssl.SSLHandshakeException` when trying to resolve dependencies, so I can't even compile the project...

**Comment by kailuowang** [comment]
@mihaisoloi  you might need to update to the latest Java 8.

**Comment by mihaisoloi** [comment]
@kailuowang thanks, that did it

**Comment by mihaisoloi** [comment]
@kailuowang when running the `sbtPlaySwagger/scripted` we get this error, which doesn't say much, and I'm kind of stuck.

```
[info] [error] (run-main-0) java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
[info] [error] java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
[info] [error]  at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings$lzycompute(SwaggerSpecGenerator.scala:263)
[info] [error]  at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings(SwaggerSpecGenerator.scala:262)
[info] [error]  at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$4(SwaggerSpecGenerator.scala:372)
[info] [error]  at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
[info] [error]  at scala.collection.immutable.List.foreach(List.scala:389)
[info] [error]  at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
[info] [error]  at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$2(SwaggerSpecGenerator.scala:370)
```

**Comment by mihaisoloi** [comment]
ok, I've taken a look at the `play-json` code changes to see what this might be about and I think it's a bug in there. Specifically caused by:

https://github.com/playframework/play-json/blob/master/play-json/shared/src/main/scala-2.13-/play/api/libs/json/ScalaCollectionCompat.scala#L22 

not being accessible from

https://github.com/playframework/play-json/blob/master/play-json/shared/src/main/scala/play/api/libs/json/Reads.scala#L229

though, it should be as `ScalaCollectionCompat` is `json` package private

**Comment by mihaisoloi** [comment]
@kailuowang there was a problem with `play-json` version `2.7.0` that was fixed in `2.7.1` so now all the tests should be passing

**Comment by mihaisoloi** [comment]
to be more specific, it was this back-port https://github.com/playframework/play-json/pull/230

**Comment by kailuowang** [comment]
this is great! thanks!

**Pull request merged**
