### PR TITLE
Adding support for Scala enums in SwaggerParameterMapper

### PR DESCRIPTION
**Pull request by mosche**
Hey @kailuowang 
finally found some time to start integrating the plugin :)
Here's a PR to add support for scala enumerations as well. Hope that's fine...

Btw, really like  the `swagger-custom-mappings.yml`!

Best, Moritz

### CODE REVIEW

**Comment by kailuowang** [comment]
LGTM, thanks very much!

**Comment by kailuowang** [comment]
Shall I release with this change now? Just want to double check with you to see if you plan to add any other change.

**Comment by mosche** [comment]
Great, thanks for the quick response :)
I have currently no rush for a release, so whatever is convenient for you.

**Comment by chafikhnini** [comment]
Thanks @mosche for this PR ;)

Could you please add a few lines about it in the documentation because I could not figure out how to make it work. I defined the following enum in my Scala code :

```
object Mode extends Enumeration {
    type Mode = Value
    val MODE1, MODE2, MODE3 = Value
}
```

And using it like this in my routes file :

```
#      schema:
#        $ref: '#/definitions/models.Protocol.Mode'
#      default: MODE1
```

throws the big `scala.ScalaReflectionException: class models.Protocol.Mode in JavaMirror with URLClassLoader with NativeCopyLoader with RawResources(...`

Is the `EnumContainer` used in your tests mandatory to wrap the enum ?

Thanks again.

**Comment by mosche** [comment]
@chafikhnini Unfortunately scala enums are really tricky outside of any "container" due to type erasure :/

`play-swagger` attempts to dealias all members of a case class. An enumeration type alias is de-aliased into a `Value` that way. To avoid unnecessary checks, I only checked for scala enumerations if their canonical path is ending with `.Value`

Unfortunately, after dealiasing an unnested enumeration the required context is lost due to type erasure and the result seems to be just `Enumeration.Value` :/
Fixing this would unfortunately require fundamental changes how de-aliasing is done in the plugin.

Could you give it a quick try using the de-aliased version (ending with `Mode.Value` in your case), please. But I suspect it'll run into exactly the problem described above...
`$ref: '#/definitions/canoncial.path.Mode.Value'`

**Comment by chafikhnini** [comment]
You were right, it throws the same error even when I add `.Value`. So the enum would work only if used in a `case class` for the moment ?

**Comment by mosche** [comment]
Yes, unfortunately :( Actually could you provide the full stacktrace

**Pull request merged**
