### PR TITLE
merge master back to 2.8

### PR DESCRIPTION
**Pull request by kailuowang**

### CODE REVIEW

**Comment by Javakky-pxv** [comment]
@kailuowang 
Thanks for some reviews!
Is this PR required for the release of "0.10.7-PLAY2.8"?

**Comment by kailuowang** [comment]
> @kailuowang Thanks for some reviews! Is this PR required for the release of `0.10.7-PLAY2.8` ?

That's right. Although I don't have the time to figure out what failed the build.

**Comment by Javakky-pxv** [comment]
@kailuowang 
This appears to be due to `0.10.7-SNAPSHOT` being defined in `versions.sbt` on the `play2.8` branch.
Rebasing the `play2.8` branch in `master` or defining `0.10.7-SNAPSHOT` in `versions.sbt` and specifying the same version in `example/project/plugins.sbt` seems to solve the problem.

https://github.com/Javakky-pxv/play-swagger/pull/3

**Comment by kailuowang** [comment]
Thanks

**Pull request merged**
