### PR TITLE
Bump to sbt 1.0.3

### PR DESCRIPTION
**Pull request by aafa**
Fixes Issue https://github.com/iheartradio/play-swagger/issues/177

### CODE REVIEW

**Comment by kailuowang** [comment]
this is great, I changed the target branch to play2.6 though, that's the branch that supports 2.6, and I think we should be okay to upgrade to sbt 1.0. Do you mind fixing the conflicts?

**Comment by aafa** [comment]
Sure, done!

**Comment by kailuowang** [comment]
Thanks so much! I will release Monday

**Comment by kailuowang** [comment]
released 0.7.0 for play 2.6 and sbt 1.0.3

**Comment by aafa** [comment]
@kailuowang  Thank you!

**Comment by aafa** [comment]
Uh, with new build I got 
```
[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: swaggerConfig
[error]         at scala.Predef$.require(Predef.scala:277)
[error]         at sbt.librarymanagement.Configuration.<init>(Configuration.scala:19)
[error]         at sbt.librarymanagement.Configuration$.of(Configuration.scala:72)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.swaggerConfig$lzycompute(SwaggerPlugin.scala:11)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.swaggerConfig(SwaggerPlugin.scala:11)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.projectConfigurations(SwaggerPlugin.scala:22)
```
on sbt start.  

I wonder why tests haven't caught that :\

Gonna take a look at this in a few hours.

**Comment by aafa** [comment]
Fix https://github.com/iheartradio/play-swagger/pull/191

**Pull request merged**
