### PR TITLE
Support for nullable/x-nullable

### LINKED ISSUE #300: Add x-nullable: true for Option[T]
Newer versions of openapi-generator require the `x-nullable` vendor extension property in order to generate nullable types when using an OAS2 specification. See https://openapi-generator.tech/docs/swagger-codegen-migration#nullable and https://github.com/OpenAPITools/openapi-generator/issues/3725#issuecomment-564924448 for details.

### PR DESCRIPTION
**Pull request by kbedel**
Fixes #300 

Currently these properties are always going to be written. If you think this could cause issues, I can add support for it being behind a flag.

### CODE REVIEW

**Comment by kbedel** [comment]
@kailuowang Would it be possible to get this merged? I can also create an equivalent PR for Play 2.8 if you like

**Comment by kailuowang** [comment]
@kbedel sorry I lost track of this one. I am not sure that you need an extra field in all those places. Is it not possible to just use the `required` field? I mean if it's not required you add an `x-nullable` property?

**Comment by kbedel** [comment]
OpenAPI Generator requires the x-nullable attribute to properly generate the C# client code we are using (the issue has links to their doc and a closed issue from that side)

**Comment by kbedel** [comment]
@kailuowang Do you also need a play 2.8 version in order for this to get merged? We currently are relying on a forked version but I'd like to move back to the mainline as we move to Play 2.8

**Comment by kailuowang** [comment]
@kbedel yes if you don't mind please create a separate PR to the 2.8 branch. I'll merge both and release.

**Pull request merged**
