### PR TITLE
Make operationId more unique by adding controller

### PR DESCRIPTION
**Pull request by stereobooster**
Fix for https://github.com/iheartradio/play-swagger/issues/237

### CODE REVIEW

**Comment by stereobooster** [comment]
I don't understand why build failed.

**Comment by stereobooster** [comment]
You generate code from open API spec file, right? But this is not generated by `play-swagger`, you are talking about some external tool. What is the name of the tool?

**Comment by joprice** [comment]
We use an internal tool. Is uses the swagger json generated by this library. But I think other codegen tools make use of operationId in a similar way to generate method names. I believe operationId is also used by the swagger ui for identifying a resource, for instance, when deep linking.

 I'd prefer if we added validation to ensure uniqueness instead of changing the definition of operationId right now. 

Then we can look into modifying play-swagger to work better with codegen tools and maybe add a test that generates client code from the spec we generate. That would give me more confidence that changing operationId doesn't preclude such usage.

**Comment by stereobooster** [comment]
Maybe change it from `LiveMetaaddPlayedTracks` to `LiveMeta.addPlayedTracks`, so you can split by `.` and your can use last element in you internal element?

**Comment by joprice** [comment]
I don't think that will work with other swagger codegen tools, and I don't want to worsen that situation. 

What we generate already doesn't play nicely with them because we include periods like that as packages in definition names. The last time I checked it broke the official swagger codegen because it expected to be able to make for instance a python class like `class UserResponse`, but instead it was generated as `class com.iheart.user.UserResponse`. This could be solved by generating modules for python, but it doesn't always make sense for every language. In our internal tool, I ended up generating packages in that case, but I'd rather remove that convention from this project as well, have a flat namespace, validate it, and have the tool inject namespacing if necessary.

In this case, I think we should make operationId more flexible in general. I assume we can already override it directly in the routes file? That's the easiest fix. 

We can also pass in the operationId policy here  https://github.com/iheartradio/play-swagger/blob/master/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala#L31

That way, we can maintain the existing behavior, but let it be overridden in the sbt plugin.

**Comment by LucasRoesler** [comment]
> In this case, I think we should make operationId more flexible in general. I assume we can already override it directly in the routes file? That's the easiest fix.

I just tried this in a project and it failed. Perhaps I missed something when testing this, but adding `operationId: ListUsers` in my routes did nothing.

Admittedly, I am not a java/scala developer but this block seems to suggest that the value is always set to the call method (which is just the http verb) https://github.com/iheartradio/play-swagger/blob/031cc7b3b6608c6788d9e44b0e54f1d217cf58d5/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala#L414-L419

Even just supporting configuration of the operationId from the routes file would unblock me.

**Comment by joprice** [comment]
@LucasRoesler Thanks for looking into that. We should make that configurable from the routes file first.

**Comment by kailuowang** [comment]
@LucasRoesler `operationId` is a key name, an identifier for the swagger endpoint, so it can't get overriden by your root swagger file. I'd say the only way forward is to have a custom operation id policy class like @joprice suggested [here](https://github.com/iheartradio/play-swagger/pull/238#issuecomment-458949278)

**Pull request closed without merging**
