### PR TITLE
Support Scala 2.11 in playSwagger

### PR DESCRIPTION
**Pull request by shinichy**
This fixes https://github.com/iheartradio/play-swagger/issues/173

### CODE REVIEW

**Comment by shinichi-katayama** [comment]
@kailuowang Would you review this PR? I'd like to use this plugin in Play 2.6 + Scala 2.11 combination.

**Comment by kailuowang** [comment]
@shinichi-katayama Thanks for the contribution, I am not sure if these changes is sufficient enough to suppport cross release. Unfortunately I don't have time to work on this. If you want, you can take a look at the play2.7 branch which has cross release properly setup for 2.12 and 2.13. 
Notice the difference in build.sbt as well as project/Publish.scala.

**Comment by kailuowang** [comment]
also the best way to find out if the cross release is working is to test it by releasing it to your own bintry org (maybe under a special version)

**Comment by shinichy** [comment]
@kailuowang Thanks for your advice. I updated build.sbt and Publish.scala by referring play2.7 branch. And I confirmed that cross release is working by releasing this to my own bintray repository. Would you take a look?

https://bintray.com/shinichy/sbt-plugins/sbt-play-swagger
https://bintray.com/shinichy/maven/play-swagger

```
sbt:root> release
[info] Starting release process off commit: 0bbf3fa0f2894e8fb979793d4efcfdd43b02af46
[info] Checking remote [origin] ...
[info] Updating playSwagger...
[info] Updating ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "sbtPlaySwagger")...
[info] Done updating.
[info] Done updating.
Release version [0.9.1] : 0.9.0-scala211
Next version [0.9.1-SNAPSHOT] :
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Excluded 2 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[success] Total time: 0 s, completed Jan 6, 2020 10:46:15 PM
[info] Setting Scala version to 2.12.8 on 3 projects.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[success] Total time: 0 s, completed Jan 6, 2020 10:46:15 PM
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Excluded 2 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Updating playSwagger...
[info] Formatting 37 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "playSwagger")(test) ...
[info] Done updating.
[info] Formatting 37 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "playSwagger")(compile) ...
[info] Compiling 10 Scala sources to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.11/classes ...
[warn] there was one feature warning; re-run with -feature for details
[warn] one warning found
[info] Done compiling.
[info] Compiling 7 Scala sources and 1 Java source to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.11/test-classes ...
[info] Done compiling.
[info] NamingStrategySpec
[info] naming strategy
[info]   + none
[info]   + snake_case
[info]   + kebab-case
[info]   + lowercase
[info]   + UpperCamelCase
[info] Total for specification NamingStrategySpec
[info] Finished in 470 ms
[info] 5 examples, 0 failure, 0 error
[info] PrefixDomainModelQualifierSpec
[info] isModel with multiple packages
[info]   + returns true if the class is in one of the packages
[info]   + returns false if the class is not in any of the packages
[info] isModel with no packages
[info]   + returns false
[info] Total for specification PrefixDomainModelQualifierSpec
[info] Finished in 469 ms
[info] 3 examples, 0 failure, 0 error
[info] EnvironmentVariablesSpec
[info] EnvironmentVariables
[info]   + transform json with markup values
[info]   + return failure when using non present environment variables
[info] Total for specification EnvironmentVariablesSpec
[info] Finished in 614 ms
[info] 2 examples, 0 failure, 0 error
[info] OutputTransformerSpec
[info] OutputTransformer.traverseTransformer
[info]   + traverse and transform object and update simple paths
[info]   + traverse and transform object and update nested paths
[info]   + traverse and transform object and update array paths
[info]   + return a failure when there's a problem transforming data
[info] OutputTransformer.>=>
[info]   + return composed function
[info]   + fail if one composed function fails
[info] Total for specification OutputTransformerSpec
[info] Finished in 664 ms
[info] 6 examples, 0 failure, 0 error
[info] SwaggerParameterMapperSpec
[info] mapParam
[info]   + map org.joda.time.DateTime to integer with format epoch
[info]   override mapping to map DateTime to string with format date-time
[info]     + single DateTime
[info]     + sequence of DateTimes
[info]   + add new custom type mapping
[info]   + map Any to any with example value
[info]   + map java enum to enum constants
[info]   + map scala enum to enum constants
[info]   + map Option[Seq[T]] to item type
[info]   + map String to string without override interference
[info]   + map default value to content without quotes when provided with string without quotes
[info]   + map default value to content without quotes when provided with string with simple quotes
[info]   + map default value to content without quotes when provided with string with triple quotes
[info] Total for specification SwaggerParameterMapperSpec
[info] Finished in 714 ms
[info] 12 examples, 0 failure, 0 error
[info] SwaggerSpecGeneratorSpec
[info] full path
[info]   + combine routePath with prefix
[info]   + ignore prefix when it's just a /
[info]   + avoid double slash at the beginning
[info]   + avoid double slash at the middle
[info]   + allow internal double slash
[info]   + respect trailing slash from previous element when in route path is root /
[info]   + remove top level trailing slash
[info] getCfgFile
[info]   + valid swagger-custom-mappings yml
[info]   + invalid swagger-settings yml
[info] Total for specification SwaggerSpecGeneratorSpec
[info] Finished in 809 ms
[info] 9 examples, 0 failure, 0 error
[info] DefinitionGeneratorSpec
[info] definition
[info]   + generate name correctly
[info]   + generate from string classname
[info]   generate properties
[info]     + with correct string property
[info]     + with correct int32 property
[info]     + with correct long property
[info]     + with reference type
[info]     + with sequence of reference type
[info]     + with optional sequence of reference type
[info]   generate properties using snake case naming strategy
[info]     + with correct string property
[info]     + with correct int32 property
[info]     + with correct long property
[info]     + with reference type
[info]     + with sequence of reference type
[info]     + with optional sequence of reference type
[info]   generate properties using kebab case naming strategy
[info]     + with correct string property
[info]     + with correct int32 property
[info]     + with correct long property
[info]     + with reference type
[info]     + with sequence of reference type
[info]     + with optional sequence of reference type
[info]   + read class in Object
[info]   + read alias type in Object
[info]   + read sequence items
[info]   + read primitive sequence items
[info]   + read Optional items
[info]   with dates
[info]     + no override
[info]     + with override
[info]   with property overrides
[info]     + support simple property types
[info]     + support optional property types
[info]     + support element overrides in seq
[info] + allDefinitions
[info] Total for specification DefinitionGeneratorSpec
[info] Finished in 597 ms
[info] 31 examples, 0 failure, 0 error
[info] EnvironmentVariablesIntegrationSpec
[info] integration
[info]   + generate api with placeholders in place
[info] + fail to generate API if environment variable is not found
[info] Total for specification EnvironmentVariablesIntegrationSpec
[info] Finished in 946 ms
[info] 2 examples, 0 failure, 0 error
[info] SwaggerSpecGeneratorIntegrationSpec
[info] integration
[info]   + Use default routes file when no argument is given
[info]   + reads json comment
[info]   + reads optional field
[info]   + merge comment in
[info]   + override generated with comment in
[info]   + not generate consumes in get
[info]   + read definition from referenceTypes
[info]   + read schema of referenced type
[info]   + read seq of referenced type
[info]   + read seq of primitive type
[info]   + read definition from referenced referenceTypes
[info]   + read trait with container
[info]   + read java enum with container
[info]   + read scala enum with container
[info]   + definition property have no name
[info]   + generate post path with consumes
[info]   + generate body parameter with in
[info]   + generate body parameter without in if already provided
[info]   + does not generate for end points marked as hidden
[info]   + generate path correctly with missing type (String by default) in controller description
[info]   + generate tags for an endpoint
[info]   + generate parameter for more path
[info]   + generate tags definition
[info]   + merge tag description from base
[info]   + get both body and url params
[info]   get parameter type of
[info]     + path params
[info]     + query params
[info]   + allow multiple routes with the same path
[info]   + parse controller with custom namespace
[info]   + parse class referenced in option type
[info]   parse param with default value as optional field
[info]     + set required as false
[info]     + set in as query
[info]     + set default value
[info]   parse param with default triple quoted string value as optional field
[info]     + set required as false
[info]     + set in as query
[info]     + set default value
[info]   parse param with default string value as optional field
[info]     + set required as false
[info]     + set in as query
[info]     + set default value
[info]   + should contain schemas in responses
[info]   + should contain schemas in requests
[info]   + excluded domain object should contain only spec from swagger.json
[info]   + definition properties does not contain 'required' boolean field
[info]   + definitions exposes 'required' array if there are required properties
[info]   + definitions does not expose 'required' array if there are no required properties
[info]   + handle multiple levels of includes
[info]   + not contain tags that are empty
[info]   + handle type aliases in post body
[info]   + accept parameter references
[info]   + hide parameter set to ignore in the custom type mappings
[info]   + map parameter set according to the custom type mappings
[info]   + generate definition reference according to custom type mappings
[info]   + custom type mappings in definition should be included in required
[info]   + add operation ids
[info]   + should maintain route file order
[info]   + should retain $refs in 'swagger-custom-mappings'
[info] integration v3
[info]   + read definition from referenceTypes
[info]   + param data type values are in the correct location
[info]   + custom param data type values are in the correct location
[info] Total for specification SwaggerSpecGeneratorIntegrationSpec
[info] Finished in 362 ms
[info] 59 examples, 0 failure, 0 error
[info] Passed: Total 129, Failed 0, Errors 0, Passed 129
[success] Total time: 9 s, completed Jan 6, 2020 10:46:24 PM
[info] Setting Scala version to 2.12.8 on 3 projects.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Updating playSwagger...
[info] Updating ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "sbtPlaySwagger")...
[info] Updating ...
[info] Formatting 37 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "sbtPlaySwagger")(test) ...
[info] Done updating.
[info] Done updating.
[info] Compiling 10 Scala sources to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.12/classes ...
[info] Done updating.
[info] Formatting 37 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "sbtPlaySwagger")(compile) ...
[info] Compiling 3 Scala sources to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/sbtPlugin/target/scala-2.12/sbt-1.0/classes ...
[warn] there was one feature warning; re-run with -feature for details
[warn] one warning found
[info] Done compiling.
[info] Compiling 7 Scala sources and 1 Java source to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] Done compiling.
[info] NamingStrategySpec
[info] naming strategy
[info]   + none
[info]   + snake_case
[info]   + kebab-case
[info]   + lowercase
[info]   + UpperCamelCase
[info] Total for specification NamingStrategySpec
[info] Finished in 349 ms
[info] 5 examples, 0 failure, 0 error
[info] PrefixDomainModelQualifierSpec
[info] isModel with multiple packages
[info]   + returns true if the class is in one of the packages
[info]   + returns false if the class is not in any of the packages
[info] isModel with no packages
[info]   + returns false
[info] Total for specification PrefixDomainModelQualifierSpec
[info] Finished in 352 ms
[info] 3 examples, 0 failure, 0 error
[info] EnvironmentVariablesSpec
[info] EnvironmentVariables
[info]   + transform json with markup values
[info]   + return failure when using non present environment variables
[info] Total for specification EnvironmentVariablesSpec
[info] Finished in 476 ms
[info] 2 examples, 0 failure, 0 error
[info] OutputTransformerSpec
[info] OutputTransformer.traverseTransformer
[info]   + traverse and transform object and update simple paths
[info]   + traverse and transform object and update nested paths
[info]   + traverse and transform object and update array paths
[info]   + return a failure when there's a problem transforming data
[info] OutputTransformer.>=>
[info]   + return composed function
[info]   + fail if one composed function fails
[info] Total for specification OutputTransformerSpec
[info] Finished in 539 ms
[info] 6 examples, 0 failure, 0 error
[info] SwaggerParameterMapperSpec
[info] mapParam
[info]   + map org.joda.time.DateTime to integer with format epoch
[info]   override mapping to map DateTime to string with format date-time
[info]     + single DateTime
[info]     + sequence of DateTimes
[info]   + add new custom type mapping
[info]   + map Any to any with example value
[info]   + map java enum to enum constants
[info]   + map scala enum to enum constants
[info]   + map Option[Seq[T]] to item type
[info]   + map String to string without override interference
[info]   + map default value to content without quotes when provided with string without quotes
[info]   + map default value to content without quotes when provided with string with simple quotes
[info]   + map default value to content without quotes when provided with string with triple quotes
[info] Total for specification SwaggerParameterMapperSpec
[info] Finished in 621 ms
[info] 12 examples, 0 failure, 0 error
[info] SwaggerSpecGeneratorSpec
[info] full path
[info]   + combine routePath with prefix
[info]   + ignore prefix when it's just a /
[info]   + avoid double slash at the beginning
[info]   + avoid double slash at the middle
[info]   + allow internal double slash
[info]   + respect trailing slash from previous element when in route path is root /
[info]   + remove top level trailing slash
[info] getCfgFile
[info]   + valid swagger-custom-mappings yml
[info]   + invalid swagger-settings yml
[info] Total for specification SwaggerSpecGeneratorSpec
[info] Finished in 644 ms
[info] 9 examples, 0 failure, 0 error
[info] EnvironmentVariablesIntegrationSpec
[info] integration
[info]   + generate api with placeholders in place
[info] + fail to generate API if environment variable is not found
[info] Total for specification EnvironmentVariablesIntegrationSpec
[info] Finished in 762 ms
[info] 2 examples, 0 failure, 0 error
[info] DefinitionGeneratorSpec
[info] definition
[info]   + generate name correctly
[info]   + generate from string classname
[info]   generate properties
[info]     + with correct string property
[info]     + with correct int32 property
[info]     + with correct long property
[info]     + with reference type
[info]     + with sequence of reference type
[info]     + with optional sequence of reference type
[info]   generate properties using snake case naming strategy
[info]     + with correct string property
[info]     + with correct int32 property
[info]     + with correct long property
[info]     + with reference type
[info]     + with sequence of reference type
[info]     + with optional sequence of reference type
[info]   generate properties using kebab case naming strategy
[info]     + with correct string property
[info]     + with correct int32 property
[info]     + with correct long property
[info]     + with reference type
[info]     + with sequence of reference type
[info]     + with optional sequence of reference type
[info]   + read class in Object
[info]   + read alias type in Object
[info]   + read sequence items
[info]   + read primitive sequence items
[info]   + read Optional items
[info]   with dates
[info]     + no override
[info]     + with override
[info]   with property overrides
[info]     + support simple property types
[info]     + support optional property types
[info]     + support element overrides in seq
[info] + allDefinitions
[info] Total for specification DefinitionGeneratorSpec
[info] Finished in 660 ms
[info] 31 examples, 0 failure, 0 error
[info] SwaggerSpecGeneratorIntegrationSpec
[info] integration
[info]   + Use default routes file when no argument is given
[info]   + reads json comment
[info]   + reads optional field
[info]   + merge comment in
[info]   + override generated with comment in
[info]   + not generate consumes in get
[info]   + read definition from referenceTypes
[info]   + read schema of referenced type
[info]   + read seq of referenced type
[info]   + read seq of primitive type
[info]   + read definition from referenced referenceTypes
[info]   + read trait with container
[info]   + read java enum with container
[info]   + read scala enum with container
[info]   + definition property have no name
[info]   + generate post path with consumes
[info]   + generate body parameter with in
[info]   + generate body parameter without in if already provided
[info]   + does not generate for end points marked as hidden
[info]   + generate path correctly with missing type (String by default) in controller description
[info]   + generate tags for an endpoint
[info]   + generate parameter for more path
[info]   + generate tags definition
[info]   + merge tag description from base
[info]   + get both body and url params
[info]   get parameter type of
[info]     + path params
[info]     + query params
[info]   + allow multiple routes with the same path
[info]   + parse controller with custom namespace
[info]   + parse class referenced in option type
[info]   parse param with default value as optional field
[info]     + set required as false
[info]     + set in as query
[info]     + set default value
[info]   parse param with default triple quoted string value as optional field
[info]     + set required as false
[info]     + set in as query
[info]     + set default value
[info]   parse param with default string value as optional field
[info]     + set required as false
[info]     + set in as query
[info]     + set default value
[info]   + should contain schemas in responses
[info]   + should contain schemas in requests
[info]   + excluded domain object should contain only spec from swagger.json
[info]   + definition properties does not contain 'required' boolean field
[info]   + definitions exposes 'required' array if there are required properties
[info]   + definitions does not expose 'required' array if there are no required properties
[info]   + handle multiple levels of includes
[info]   + not contain tags that are empty
[info]   + handle type aliases in post body
[info]   + accept parameter references
[info]   + hide parameter set to ignore in the custom type mappings
[info]   + map parameter set according to the custom type mappings
[info]   + generate definition reference according to custom type mappings
[info]   + custom type mappings in definition should be included in required
[info]   + add operation ids
[info]   + should maintain route file order
[info]   + should retain $refs in 'swagger-custom-mappings'
[info] integration v3
[info]   + read definition from referenceTypes
[info]   + param data type values are in the correct location
[info]   + custom param data type values are in the correct location
[info] Total for specification SwaggerSpecGeneratorIntegrationSpec
[info] Finished in 458 ms
[info] 59 examples, 0 failure, 0 error
[info] Passed: Total 129, Failed 0, Errors 0, Passed 129
[success] Total time: 7 s, completed Jan 6, 2020 10:46:31 PM
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Setting version to '0.9.0-scala211'.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] [support_scala211_release d80bb3b] Setting version to 0.9.0-scala211
[info]  1 file changed, 1 insertion(+), 1 deletion(-)
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
Tag [v0.9.0-scala211] exists! Overwrite, keep or abort or enter a new tag (o/k/a)? [a] o
[warn] Overwriting a tag can cause problems if others have already seen the tag (see `git help tag`)!
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Excluded 2 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.11/play-swagger_2.11-0.9.0-scala211-sources.jar ...
[info] Done packaging.
[info] Wrote /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.11/play-swagger_2.11-0.9.0-scala211.pom
[info] Updating playSwagger...
[info] Formatting 2 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "playSwagger")(compile) ...
[info] Reformatted 2 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "playSwagger")(compile).
[info] Done updating.
[info] Main Scala API documentation to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.11/api...
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.11/play-swagger_2.11-0.9.0-scala211.jar ...
[info] Done packaging.
[warn] there was one feature warning; re-run with -feature for details
model contains 36 documentable templates
[warn] /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala:126:3: Could not find any member to link for "Route".
[warn]   /**
[warn]   ^
[warn] two warnings found
[info] Main Scala API documentation successful.
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.11/play-swagger_2.11-0.9.0-scala211-javadoc.jar ...
[info] Done packaging.
[info] 	published play-swagger_2.11 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.11/0.9.0-scala211/play-swagger_2.11-0.9.0-scala211.pom
[info] 	published play-swagger_2.11 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.11/0.9.0-scala211/play-swagger_2.11-0.9.0-scala211.jar
[info] 	published play-swagger_2.11 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.11/0.9.0-scala211/play-swagger_2.11-0.9.0-scala211-sources.jar
[info] 	published play-swagger_2.11 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.11/0.9.0-scala211/play-swagger_2.11-0.9.0-scala211-javadoc.jar
[info] shinichy/play-swagger@0.9.0-scala211 was released
[success] Total time: 16 s, completed Jan 6, 2020 10:47:17 PM
[info] Setting Scala version to 2.12.8 on 3 projects.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.12/play-swagger_2.12-0.9.0-scala211-sources.jar ...
[info] Done packaging.
[info] Wrote /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.12/play-swagger_2.12-0.9.0-scala211.pom
[info] Updating playSwagger...
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/sbtPlugin/target/scala-2.12/sbt-1.0/sbt-play-swagger-0.9.0-scala211-sources.jar ...
[info] Done packaging.
[info] Done updating.
[info] Main Scala API documentation to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.12/api...
[info] Updating ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "sbtPlaySwagger")...
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.12/play-swagger_2.12-0.9.0-scala211.jar ...
[info] Formatting 2 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "sbtPlaySwagger")(compile) ...
[info] Done packaging.
[info] Reformatted 2 Scala sources ProjectRef(uri("file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/"), "sbtPlaySwagger")(compile).
[warn] there was one feature warning; re-run with -feature for details
model contains 36 documentable templates
[info] Done updating.
[info] Compiling 1 Scala source to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/sbtPlugin/target/scala-2.12/sbt-1.0/classes ...
[info] Main Scala API documentation to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/sbtPlugin/target/scala-2.12/sbt-1.0/api...
[info] Done compiling.
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/sbtPlugin/target/scala-2.12/sbt-1.0/sbt-play-swagger-0.9.0-scala211.jar ...
[info] Done packaging.
[warn] /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala:126:3: Could not find any member to link for "Route".
[warn]   /**
[warn]   ^
[warn] two warnings found
[info] Main Scala API documentation successful.
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/core/target/scala-2.12/play-swagger_2.12-0.9.0-scala211-javadoc.jar ...
model contains 11 documentable templates
[info] Done packaging.
[info] Main Scala API documentation successful.
[info] Packaging /Users/shinichi/.ghq/github.com/shinichy/play-swagger/sbtPlugin/target/scala-2.12/sbt-1.0/sbt-play-swagger-0.9.0-scala211-javadoc.jar ...
[info] Done packaging.
[info] 	published play-swagger_2.12 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.12/0.9.0-scala211/play-swagger_2.12-0.9.0-scala211.pom
[info] 	published play-swagger_2.12 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.12/0.9.0-scala211/play-swagger_2.12-0.9.0-scala211.jar
[info] 	published play-swagger_2.12 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.12/0.9.0-scala211/play-swagger_2.12-0.9.0-scala211-sources.jar
[info] 	published play-swagger_2.12 to https://api.bintray.com/maven/shinichy/maven/maven/com/iheart/play-swagger_2.12/0.9.0-scala211/play-swagger_2.12-0.9.0-scala211-javadoc.jar
[info] :: delivering :: com.iheart#sbt-play-swagger;0.9.0-scala211 :: 0.9.0-scala211 :: release :: Mon Jan 06 22:47:34 PST 2020
[info] 	delivering ivy file to /Users/shinichi/.ghq/github.com/shinichy/play-swagger/sbtPlugin/target/scala-2.12/sbt-1.0/ivy-0.9.0-scala211.xml
[info] shinichy/play-swagger@0.9.0-scala211 was released
[info] 	published sbt-play-swagger to com.iheart/sbt-play-swagger/scala_2.12/sbt_1.0/0.9.0-scala211/jars/sbt-play-swagger.jar
[info] 	published sbt-play-swagger to com.iheart/sbt-play-swagger/scala_2.12/sbt_1.0/0.9.0-scala211/srcs/sbt-play-swagger-sources.jar
[info] 	published sbt-play-swagger to com.iheart/sbt-play-swagger/scala_2.12/sbt_1.0/0.9.0-scala211/docs/sbt-play-swagger-javadoc.jar
[info] 	published ivy to com.iheart/sbt-play-swagger/scala_2.12/sbt_1.0/0.9.0-scala211/ivys/ivy.xml
[info] shinichy/sbt-play-swagger@0.9.0-scala211 was released
[success] Total time: 29 s, completed Jan 6, 2020 10:47:47 PM
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] Setting version to '0.9.1-SNAPSHOT'.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/shinichi/.ghq/github.com/shinichy/play-swagger/)
[info] [support_scala211_release 78cb463] Setting version to 0.9.1-SNAPSHOT
[info]  1 file changed, 1 insertion(+), 1 deletion(-)
Push changes to the remote repository (y/n)? [y] n
[warn] Remember to push the changes yourself!
```

**Comment by shinichy** [comment]
BTW, @shinichi-katayama  is my company Github account. It's same as @shinichy.

**Comment by kailuowang** [comment]
@shinichy released 0.9.1 on both 2.11 and 2.12 thanks again for the contribution.

**Comment by shinichi-katayama** [comment]
@kailuowang Great! Thank you for reviewing and releasing it!

**Pull request merged**
