### PR TITLE
cross building sbt 1.0 version

### PR DESCRIPTION
**Pull request by wlk**
refers to https://github.com/iheartradio/play-swagger/issues/177

* bumped scala version to 2.11.11
* bumped sbt plugins to their latest versions
* after upgrading sbt-scalariform the defaults have changed and this resulted in code reformatting
* added cross building for sbt plugins as described in http://www.scala-sbt.org/1.x/docs/Cross-Build-Plugins.html

I'm not sure if this is really what's needed, created PR to get initial feedback (I'll clean up the PR later)

The more straighforward upgrade to sbt 1.0 is blocked by this issue: https://github.com/scoverage/sbt-coveralls/issues/95 the sbt-coveralls plugin used in this project doesn't support sbt 1.0 just yet (it's the only one that's not yet migrated)
Also the Scala 2.12 upgrade is blocked by json4s-native, I haven't checked exactly how to go about it, but upgrading to something newer (which has scala 2.12 releases) will create compilation failures - this is the related issue: https://github.com/json4s/json4s/issues/212

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks so much for doing this!
Some thoughts:
1. How about we make upgrade of sbt-scalariform a separate PR so that reformat change can be separated out.
2. I'd rather go the straightforward way to do sbt cross build. If sbt-coverall is the blocker, let's disable it for now. I can either reenanble it after its sbt 1.0 upgrade is released or switch to codecov which is better anyway.

**Comment by kailuowang** [comment]
sorry, accidently clicked the close button .

**Comment by wlk** [comment]
Thanks @kailuowang I'll create smaller PRs to upgrade dependencies, and will disable `sbt-coveralls` as this is the blocker now

**Comment by kailuowang** [comment]
thanks. It's merged

**Comment by wlk** [comment]
closing this PR, will be handled in few smaller ones

**Pull request closed without merging**
