### PR TITLE
V0.6.2 play2.6 2.11

### PR DESCRIPTION
**Pull request by pocman**
Naive approach trying to solve https://github.com/iheartradio/play-swagger/issues/173

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks for your contribution, but obviously we can't merge this in as is, it will stop support 2.12.

**Comment by pocman** [comment]
Why does the v0.6.2-PLAY2.6 have to be built on scala 2.12 ?
Can't we publish this branch on bintray to fix #173 ?

**Comment by kailuowang** [comment]
I am not asking you to upgrade scala 2.12, but I am just curious what prevented you from it?

**Comment by pocman** [comment]
We have a lot of internal jars and we are still in the process of migrating them.

**Comment by kailuowang** [comment]
If it's just a temporary thing, I would just publish your version of scala2.11 jar to an internal maven repo for now. and wait for playswagger to get proper cross-building for play 2.6. now that play 2.6 is on sbt1.0, it may become easier (since sbt 1.0 supports scala 2.11 and scala 2.12)

**Comment by pocman** [comment]
Ok, thanks.
We have an internal maven, this branch is working fine for me. 
I was more thinking about other user such as @samupra

**Pull request closed without merging**
