### PR TITLE
Improve collections and refined type support

### PR DESCRIPTION
**Pull request by bpiper**
See #362.

### CODE REVIEW

**Comment by zcabjro** [comment]
I have a project that would benefit from this -- thank you! I believe https://github.com/iheartradio/play-swagger/pull/364 will fix the upstream issue that is causing CI checks to fail for this one.

**Comment by zcabjro** [comment]
@bpiper Has there been any update on this? If not I can try to get it landed if that helps

**Comment by bpiper** [comment]
@zcabjro no, this is still waiting for a review from someone with write access.  I've pulled your CI fix into my fork, in any case.

**Review by kailuowang — APPROVED** [review]
Thanks!

**Comment by kailuowang** [comment]
Release 0.10.3-PLAY2.8

**Pull request merged**
