### PR TITLE
Support Play 2.6 and Scala 2.12

### PR DESCRIPTION
**Pull request by canyaman**
Prepare the plugin for [sbt 1.0](http://developer.lightbend.com/blog/2017-04-18-sbt-1-0-roadmap-and-beta1/) and scala 2.12
- Update play version to 2.6.0-M5
- Update sbt version to 0.13.15
- Remove deprecated sbt 0.12 style dependecy operators
- Update other libraries and plugins

### CODE REVIEW

**Comment by kailuowang** [comment]
This is awesome. And I am bit surprised that all tests pass without code change. I am curious have you actually tried this in a play 2.6 app? 
On the other hand I am not sure if we want to tie our master branch to play 2.6 milestone release yet. I just created a play2.6 branch, do you mind change your PR to target that branch instead?

**Comment by canyaman** [comment]
play_2.6 branch is better place for that PR. I'm trying to use Scala 2.12 & play 2.6 on the test servers but I'm using CI pipeline for deployment. If this snopshot version public, everything is fine. We can test on the web without extra effort. 
Can you publish the plugin as "0.7.0-PLAY2.6"?

**Comment by kailuowang** [comment]
since there is no breaking change, I am going to publish 0.6.1-Play2.6-M5

**Comment by kailuowang** [comment]
Would you be kind enough to update this PR to exclude the scala 2.12 and play 2.6 update but include all the other improvements on build files? things like 
```
scripted := scripted.dependsOn(publishLocal in playSwagger).evaluated
```

**Comment by kailuowang** [comment]
closing as this is replaced by other PRs that were already merged.

**Pull request closed without merging**
