### PR TITLE
Update sbt version and add Play 2.5 support

### PR DESCRIPTION
**Pull request by russwyte**
Needed some swagger in my APIs I am migrating to Play 2.5.

Tests pass, and my swagger docs are working again.

### CODE REVIEW

**Comment by kailuowang** [comment]
thanks! what about  https://github.com/iheartradio/play-swagger/issues/56?

**Comment by russwyte** [comment]
Fixes #56

**Comment by kailuowang** [comment]
This might break compatibility with play 2.4. Do you happen to also have a play2.4 app that you can test with?

**Comment by russwyte** [comment]
I will give that a try right now.

**Comment by russwyte** [comment]
Indeed unfortunately it does break compatibility with 2.4... Not sure how to resolve that.

**Comment by russwyte** [comment]
Get the same error as I got in #56

**Comment by kailuowang** [comment]
Thanks, I am going to create a temporary release just for 2.5, do you mind remove the changes you made in version.sbt and retarget the PR to the play-2.5 branch?

**Comment by russwyte** [comment]
Superseded by #58

**Pull request closed without merging**
